#################################################################
## Energy
#################################################################

        ##########################################################
        ## Set Winter Rate First 750
        ##########################################################

- alias: Energy - Set Winter Rate First 750
  id: 'energy_set_winter_rate_first_750'

  trigger:
    - platform: state
      entity_id: 
          - sensor.monthly_electric

  condition:
    - condition: template
      value_template: "{{ now().month in [1,2,3,4,5,10,11,12] }}"
    - condition: template
      value_template: '{{ trigger.to_state.state | float(0) < 750000 }}'

  action:
    - service: select.select_option
      data:
        entity_id: select.monthly_electric
        option: "Winter Rate First 750"

        ##########################################################
        ## Set Winter Rate Over 750
        ##########################################################

- alias: Energy - Set Winter Rate Over 750
  id: 'energy_set_winter_rate_over_750'

  trigger:
    - platform: state
      entity_id: 
          - sensor.monthly_electric

  condition:
    - condition: template
      value_template: "{{ now().month in [1,2,3,4,5,10,11,12] }}"
    - condition: template
      value_template: '{{ trigger.to_state.state | float(0) > 749999 }}'

  action:
    - service: select.select_option
      data:
        entity_id: select.monthly_electric
        option: "Winter Rate Over 750"

        ##########################################################
        ## Set Summer Rate
        ##########################################################

- alias: Energy - Set Summer Rate
  id: 'energy_set_summer_rate'

  trigger:
    - platform: state
      entity_id: 
          - sensor.monthly_electric

  condition:
    - condition: template
      value_template: "{{ now().month in [6,7,8,9] }}"

  action:
    - service: select.select_option
      data:
        entity_id: select.monthly_electric
        option: "Summer Rate"