#################################################################
## Network
#################################################################

        ##########################################################
        ## Retart att Router Daily
        ##########################################################

- alias: Network - Retart att Router Daily
  id: 'network_restart_att_router_daily'

  trigger:
    - platform: time
      at: '00:00:00'

  condition:
    - condition: state
      entity_id: switch.att_router
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.att_router
    - delay: '00:00:15'
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        ##########################################################
        ## WAN Down Restart at&t Router
        ##########################################################

- alias: Network - WAN Down Restart att Router
  id: 'network_wan_down_restart_att_router'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 60
        seconds: 0

  condition:
    - condition: state
      entity_id: binary_sensor.wan
      state: 'off'
    - condition: state
      entity_id: switch.att_router
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.att_router
    - delay: '00:00:15'
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        ##########################################################
        ## Turn on att Router when Off
        ##########################################################

- alias: Network - Turn on att Router when Off
  id: 'network_turn_on_att_router_when_off'

  trigger:
    - platform: state
      entity_id: switch.att_router
      to: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.att_router
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        #################################################################
        ## WAN Down On Startup Turn On at&t Router
        #################################################################

- alias: network - WAN Down On Startup Turn On att Router
  id: 'network_wan_down_on_startup_turn_on_att_router'

  trigger:
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: binary_sensor.wan
      state: 'off'
    - condition: state
      entity_id: switch.att_router
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.att_router
    - delay: 00:10:00
    - service: switch.turn_on
      entity_id:
        - switch.att_router
    - delay: 00:10:00
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        ##########################################################
        ## Turn On at&t Router in Vacation Mode
        ##########################################################

- alias: network - Turn On att Router in Vacation Mode
  id: 'network_turn_on_att_router_in_vacation_mode'

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: switch.att_router
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id: switch.att_router

        ##########################################################
        ## Turn On at&t Router when Away
        ##########################################################

- alias: network - Turn On att Router when Away
  id: 'network_turn_on_att_router_when_away'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: switch.att_router
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.att_router

        ##########################################################
        ## Household Away Turn Off Camera Privacy Mode
        ##########################################################

- alias: Network - Household Away Turn Off Camera Privacy Mode
  id: 'network_household_away_turn_off_camera_privacy_mode'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.basement_camera_privacy_mode
        - switch.living_room_camera_privacy_mode
        - switch.kitchen_camera_privacy_mode

        ##########################################################
        ## Household Away Turn On Camera Privacy Mode
        ##########################################################

- alias: Network - Household Away Turn On Camera Privacy Mode
  id: 'network_household_home_turn_on_camera_privacy_mode'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.basement_camera_privacy_mode
        - switch.living_room_camera_privacy_mode
        - switch.kitchen_camera_privacy_mode

        ##########################################################
        ## Re-Enable Pi-hole After 15 Mins
        ##########################################################

- alias: Network - Re-Enable Pi-hole After 15 Mins
  id: 'network_reenable_pihole_after_15_mins'

  trigger:
    - platform: state
      entity_id: switch.pihole
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.pihole
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.pihole

#################################################################
## Notifications
#################################################################

    #################################################################
    ## WAN Down Notification
    #################################################################

- alias: Network - WAN Down Notification
  id: 'network_wan_down_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Internet is Down!
        data:
          tag: network
          group: network

    #################################################################
    ## WAN Up Notification
    #################################################################

- alias: Network - WAN Up Notification
  id: 'network_wan_up_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.mobile_app_USER1s_iphone
      data:
        message: Internet is Up
        data:
          tag: network
          group: network
